"""empty message

Revision ID: 9f92f1e1de67
Revises: 
Create Date: 2018-06-29 16:40:41.191761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f92f1e1de67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_users', sa.Column('password', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_users', 'password')
    # ### end Alembic commands ###
